direction: left
grid-columns: 2

ds: Data Science {
    grid-columns: 2

    py: Python {
        grid-rows: 9

        Data Wrangling.pandas
        Data Wrangling.polars
        Data Wrangling.duckdb

        Data Visualisation.seaborn
        Data Visualisation.matplotlib

        Machine Learning.scikit-learn
        Machine Learning.numpy
        Machine Learning.XGBoost
        Machine Learning.statsmodels
        Machine Learning.scipy

        Deep Learning.TensorFlow
        Deep Learning.PyTorch
        Deep Learning.keras

        Hyperparameter Tuning.Hyperopt
        Hyperparameter Tuning.tpot

        Parallel Computing.PySpark(SparkSQL, MLlib)

        LLM.evaluate
        LLM.trl
        LLM.tiktoken

        Natural Language Processing.re
        Natural Language Processing.NLTK
        Natural Language Processing.Gensim
        Natural Language Processing.polyglot
        Natural Language Processing.spaCy

        Database.SQLAlchemy

        Image Processing.scikit-image

        Impuation.fancyimpute

        Bayesian.numpyro
        Bayesian.PyMC
        Bayesian.PyStan

        Data Validation.patito

        Testing.pytest
        Testing.unittest

        Monitoring.NannyML

        Web Scraping.urllib
        Web Scraping.requests
        Web Scraping.BeautifulSoup
        Web Scraping.scrapy
        Web Scraping.Selenium

        GIS Data.GeoPandas
        GIS Data.GeoJSON
        GIS Data.GeoSeries
        GIS Data.folium

        Privacy-enhancing Techniques.faker
        Privacy-enhancing Techniques.diffprivlib
        Privacy-enhancing Techniques.SDV
        Privacy-enhancing Techniques.smartnoise

        Presentation.marimo
    }

    r: R {
        grid-rows: 4

        Data Wrangling.tidyverse

        Data Visualisation.ggplot2

        Machine Learning.caret
        Machine Learning.mlr
        Machine Learning.h2o
        Machine Learning.broom

        Bayesian.rstan
        Bayesian.inla
        Bayesian.jags

        Presentation.Shiny
        Presentation.RMarkDown
    }

    concepts: Concepts / Theories{
        grid-rows: 8

        Machine Learning
        Data Visualisation
        Bayesian Data Analysis
        Hyperparameter Tuning
        Data Wrangling
        EDA
        Statistical Computing
        Time Series
        Natural Language Processing
        Deep Learning (NN, CNN, RNN)
        Image Processing
        Parallel Computing
        Feature Engineering
        Statistical Simulation
        Recommendation System
        LLM (Transformer, Agent)
        Prompt Engineering
        RAG (Embedding)
        LLM Fine-tuning (LoRA)
    }
}

db: Database{
    grid-rows: 3

    SQL.MySQL
    SQL.PostgreSQL
    SQL.DuckDB

    SQL / NoSQL.Snowflake

    NoSQL.MongoDB
    NoSQL.Redis

    Graph Database.Neo4j

    Concepts / Theories.Relational Database
    Concepts / Theories.NoSQL Database
    Concepts / Theories.Datawarehousing
}

mlops: MLOps{
    grid-rows: 3

    CI / CD.Shell
    CI / CD.Bash
    CI / CD.MLFlow
    CI / CD.Feast
    CI / CD.Git
    CI / CD.GitHub Actions (CML)
    CI / CD.YAML

    Containerisation.Docker
    Containerisation.Kubernetes

    Clouds.AWS (EC2, RDS, S3, EB)
    Clouds.BigQuery

    Data Engineering.Apache
    Data Engineering.Apache Airflow
    Data Engineering.Apache Kafka
    Data Engineering.dbt
    Data Engineering.DVC

    Concepts / Theories.Cloud Computing
    Concepts / Theories.ETL / ELT
    Concepts / Theories.Streaming
    Concepts / Theories.Deployment
    Concepts / Theories.Monitoring
    Concepts / Theories.CI / CD / CT / CM
}

others: Data-related Skills{
    grid-rows: 2

    Programming Language.Julia
    Programming Language.C++

    LLM.HuggingFace
    LLM.OpenAI API
    LLM.Chroma
    LLM.LangChain
    LLM.Llama 3
    LLM.Pinecone
    LLM.Ollama

    Concepts / Theories.Build Web Application
    Concepts / Theories.Data Privacy and Anonymisation
    Concepts / Theories.Web Scraping
}